# Generated by Django 6.0.7 on 2026-08-05 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HojaVida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('vida_util', models.PositiveIntegerField(default=10, help_text='Vida útil en años')),
                ('garantia_hasta', models.DateField(blank=True, null=True)),
                ('costo_adquisicion', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('ubicacion_detallada', models.CharField(blank=True, max_length=250)),
                ('manual_operacion', models.FileField(blank=True, null=True, upload_to='manuales/')),
                ('manual_servicio', models.FileField(blank=True, null=True, upload_to='manuales_servicio/')),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='equipos/')),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hoja_vida', to='equipos.equipo')),
            ],
            options={
                'verbose_name': 'Hoja de Vida',
                'verbose_name_plural': 'Hojas de Vida',
                'ordering': ['equipo'],
            },
        ),
    ]
