# Generated by Django 6.0.7 on 2026-08-24 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_catalogoequipo_options_and_more'),
        ('hojas_vida', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hojavida',
            name='manual_operacion',
        ),
        migrations.RemoveField(
            model_name='hojavida',
            name='manual_servicio',
        ),
        migrations.AddField(
            model_name='hojavida',
            name='alimentacion_agua',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='alimentacion_aire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='alimentacion_baterias',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='alimentacion_electricidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='alimentacion_emergencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='alimentacion_estandar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='alimentacion_oxigeno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='alimentacion_regulada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='alimentacion_servicio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='alimentacion_vacio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='alimentacion_vapor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='fabricante_ciudad_pais',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='fabricante_telefono',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='fecha_fabricacion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='forma_adquisicion',
            field=models.CharField(blank=True, choices=[('COMPRA', 'Compra'), ('DONACION', 'Donación'), ('COMODATO', 'Comodato'), ('ARRIENDO', 'Arriendo'), ('TRANSFERENCIA', 'Transferencia'), ('OTRO', 'Otro')], max_length=30),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='garantia_anios',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='periodicidad_calibracion',
            field=models.CharField(blank=True, choices=[('BIMENSUAL', 'Bimensual'), ('CUATRIMESTRAL', 'Cuatrimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual'), ('NO_APLICA', 'No aplica')], max_length=30),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='periodicidad_mantenimiento',
            field=models.CharField(blank=True, choices=[('TRIMESTRAL', 'Trimestral'), ('CUATRIMESTRAL', 'Cuatrimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual'), ('NO_APLICA', 'No aplica')], max_length=30),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='proveedor_ciudad_pais',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='proveedor_telefono',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='recomendaciones_fabricante',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='registro_importacion',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='riesgo_electrico',
            field=models.CharField(choices=[('NO_APLICA', 'No aplica'), ('CLASE_I', 'Clase I'), ('CLASE_II', 'Clase II'), ('CLASE_III', 'Clase III')], default='NO_APLICA', max_length=20),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='tecnologia_predominante',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='AccesorioHojaVida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('nombre', models.CharField(max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('hoja_vida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesorios', to='hojas_vida.hojavida')),
            ],
            options={
                'verbose_name': 'Accesorio de Hoja de Vida',
                'verbose_name_plural': 'Accesorios de Hoja de Vida',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DocumentacionHojaVida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MANUAL_SERVICIO', 'Manual de servicios'), ('MANUAL_OPERACION', 'Manual de operación'), ('PLANOS', 'Planos'), ('DIAGRAMA_PARTES', 'Diagrama de partes'), ('OTROS', 'Otros')], max_length=30)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('archivo', models.FileField(upload_to='hojas_vida/documentos/')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('hoja_vida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='hojas_vida.hojavida')),
            ],
            options={
                'verbose_name': 'Documento de Hoja de Vida',
                'verbose_name_plural': 'Documentos de Hojas de Vida',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ValorCampoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField(blank=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valores', to='catalogo.campotecnico')),
                ('hoja_vida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_tecnicos', to='hojas_vida.hojavida')),
            ],
            options={
                'verbose_name': 'Valor de Característica Técnica',
                'verbose_name_plural': 'Valores de Características Técnicas',
                'ordering': ['campo__orden', 'campo__nombre'],
                'constraints': [models.UniqueConstraint(fields=('hoja_vida', 'campo'), name='unique_valor_campo_hoja_vida')],
            },
        ),
    ]
