# Generated by Django 6.0.7 on 2026-08-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojas_vida', '0002_remove_hojavida_manual_operacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojavida',
            name='fecha_sincronizacion_catalogo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='nombre_catalogo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
