# Generated by Django 6.0.7 on 2026-08-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojas_vida', '0003_hojavida_fecha_sincronizacion_catalogo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojavida',
            name='descripcion_catalogo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='frecuencia_mantenimiento_catalogo',
            field=models.PositiveIntegerField(blank=True, help_text='Frecuencia definida por el catálogo, en meses', null=True),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='requiere_calibracion_catalogo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='requiere_mantenimiento_catalogo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='riesgo_invima',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='tecnologia_catalogo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
