# Generated by Django 6.0.7 on 2026-08-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojas_vida', '0004_hojavida_descripcion_catalogo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojavida',
            name='fabricante',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
