# Generated by Django 6.0.7 on 2026-08-04 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituciones', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('inventario', models.CharField(blank=True, max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('serie', models.CharField(blank=True, max_length=100)),
                ('fabricante', models.CharField(blank=True, max_length=150)),
                ('registro_invima', models.CharField(blank=True, max_length=100)),
                ('riesgo', models.CharField(choices=[('I', 'Clase I'), ('IIA', 'Clase IIA'), ('IIB', 'Clase IIB'), ('III', 'Clase III')], default='I', max_length=5)),
                ('tecnologia', models.CharField(choices=[('BIOMEDICO', 'Equipo Biomédico'), ('INDUSTRIAL', 'Industrial'), ('LABORATORIO', 'Laboratorio'), ('IMAGENOLOGIA', 'Imagenología')], default='BIOMEDICO', max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('MANTENIMIENTO', 'En mantenimiento'), ('FUERA_SERVICIO', 'Fuera de servicio'), ('BAJA', 'Dado de baja')], default='ACTIVO', max_length=30)),
                ('frecuencia_mantenimiento', models.PositiveIntegerField(default=6, help_text='Frecuencia en meses')),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('fecha_proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='instituciones.institucion')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['institucion', 'servicio', 'nombre'],
            },
        ),
    ]
