# Generated by Django 6.0.7 on 2026-08-05 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_equipo_catalogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='frecuencia_mantenimiento',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='riesgo',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='tecnologia',
        ),
    ]
