# Generated by Django 6.0.7 on 2026-08-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('riesgo', models.CharField(choices=[('I', 'Clase I'), ('IIA', 'Clase IIA'), ('IIB', 'Clase IIB'), ('III', 'Clase III')], default='I', max_length=5)),
                ('tecnologia', models.CharField(choices=[('BIOMEDICO', 'Equipo Biomédico'), ('LABORATORIO', 'Laboratorio'), ('IMAGENOLOGIA', 'Imagenología'), ('INDUSTRIAL', 'Industrial')], default='BIOMEDICO', max_length=20)),
                ('requiere_calibracion', models.BooleanField(default=False)),
                ('requiere_mantenimiento', models.BooleanField(default=True)),
                ('frecuencia_mantenimiento', models.PositiveIntegerField(default=6, help_text='Frecuencia en meses')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catálogo de Equipo',
                'verbose_name_plural': 'Catálogo de Equipos',
                'ordering': ['nombre'],
            },
        ),
    ]
