# Generated by Django 6.0.7 on 2026-08-05 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('activa', models.BooleanField(default=True)),
                ('catalogo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plantilla', to='catalogo.catalogoequipo')),
            ],
            options={
                'verbose_name': 'Plantilla de Inspección',
                'verbose_name_plural': 'Plantillas de Inspección',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ItemPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('obligatorio', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalogo.plantillainspeccion')),
            ],
            options={
                'verbose_name': 'Ítem',
                'verbose_name_plural': 'Ítems',
                'ordering': ['orden'],
            },
        ),
    ]
