# Generated by Django 6.0.7 on 2026-08-24 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_plantillainspeccion_itemplantilla'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogoequipo',
            options={'ordering': ['nombre'], 'verbose_name': 'Catálogo de Equipo', 'verbose_name_plural': 'Catálogos de Equipos'},
        ),
        migrations.AlterModelOptions(
            name='itemplantilla',
            options={'ordering': ['orden'], 'verbose_name': 'Ítem de Inspección', 'verbose_name_plural': 'Ítems de Inspección'},
        ),
        migrations.CreateModel(
            name='GuiaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('activa', models.BooleanField(default=True)),
                ('catalogo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guia_mantenimiento', to='catalogo.catalogoequipo')),
            ],
            options={
                'verbose_name': 'Guía de Mantenimiento',
                'verbose_name_plural': 'Guías de Mantenimiento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ActividadMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('obligatorio', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='catalogo.guiamantenimiento')),
            ],
            options={
                'verbose_name': 'Actividad de Mantenimiento',
                'verbose_name_plural': 'Actividades de Mantenimiento',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='CampoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_dato', models.CharField(choices=[('TEXTO', 'Texto'), ('NUMERO', 'Número'), ('DECIMAL', 'Número decimal'), ('FECHA', 'Fecha'), ('SI_NO', 'Sí / No')], default='TEXTO', max_length=20)),
                ('unidad', models.CharField(blank=True, help_text='Ejemplo: V, A, kg, Hz, °C', max_length=50)),
                ('obligatorio', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_tecnicos', to='catalogo.catalogoequipo')),
            ],
            options={
                'verbose_name': 'Campo Técnico',
                'verbose_name_plural': 'Campos Técnicos',
                'ordering': ['orden', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('catalogo', 'nombre'), name='unique_campo_tecnico_catalogo')],
            },
        ),
    ]
