# Generated by Django 6.0.7 on 2026-08-05 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_plantillainspeccion_itemplantilla'),
        ('equipos', '0003_remove_equipo_frecuencia_mantenimiento_and_more'),
        ('instituciones', '0001_initial'),
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora_inicio', models.DateTimeField(auto_now_add=True)),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('FINALIZADA', 'Finalizada')], default='ABIERTA', max_length=20)),
                ('observaciones_generales', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('biomedico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones', to='instituciones.institucion')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Inspección',
                'verbose_name_plural': 'Inspecciones',
                'ordering': ['-fecha', '-hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='FirmaInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable_servicio', models.CharField(max_length=150)),
                ('firma_biomedico', models.ImageField(blank=True, null=True, upload_to='firmas/biomedicos/')),
                ('firma_responsable', models.ImageField(blank=True, null=True, upload_to='firmas/responsables/')),
                ('fecha_firma', models.DateTimeField(auto_now_add=True)),
                ('inspeccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firma', to='inspecciones.inspeccion')),
            ],
            options={
                'verbose_name': 'Firma de inspección',
                'verbose_name_plural': 'Firmas de inspección',
            },
        ),
        migrations.CreateModel(
            name='DetalleInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('OBSERVACION', 'Con observaciones'), ('FUERA_SERVICIO', 'Fuera de servicio')], default='OPERATIVO', max_length=30)),
                ('limpio', models.BooleanField(default=True)),
                ('energiza', models.BooleanField(default=True)),
                ('accesorios_completos', models.BooleanField(default=True)),
                ('alarmas_funcionan', models.BooleanField(default=True)),
                ('funcionamiento_correcto', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones', to='equipos.equipo')),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inspecciones.inspeccion')),
            ],
            options={
                'verbose_name': 'Detalle de inspección',
                'verbose_name_plural': 'Detalles de inspección',
                'ordering': ['equipo__nombre'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumple', models.BooleanField(default=True)),
                ('observacion', models.TextField(blank=True)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='inspecciones.detalleinspeccion')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='catalogo.itemplantilla')),
            ],
            options={
                'verbose_name': 'Resultado de ítem',
                'verbose_name_plural': 'Resultados de ítems',
                'ordering': ['item__orden'],
                'unique_together': {('detalle', 'item')},
            },
        ),
    ]
