# Generated by Django 6.0.7 on 2026-08-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmainspeccion',
            name='observaciones_finales',
            field=models.TextField(blank=True),
        ),
    ]
