# Generated by Django 6.0.7 on 2026-09-02 01:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0003_remove_equipo_frecuencia_mantenimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calibracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calibracion', models.DateField(verbose_name='Fecha de calibración')),
                ('codigo', models.CharField(max_length=100, verbose_name='Código de calibración')),
                ('empresa', models.CharField(max_length=200, verbose_name='Empresa que realizó la calibración')),
                ('certificado', models.FileField(upload_to='calibraciones/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Certificado de calibración')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibraciones', to='equipos.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Calibración',
                'verbose_name_plural': 'Calibraciones',
                'ordering': ['-fecha_calibracion', '-creado'],
            },
        ),
    ]
