# Generated by Django 6.0.7 on 2026-08-10 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojas_vida', '0001_initial'),
        ('mantenimiento', '0001_initial'),
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='hoja_vida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='hojas_vida.hojavida', verbose_name='Hoja de vida'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='ingeniero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='Número de orden')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('empresa', models.CharField(blank=True, max_length=200, verbose_name='Empresa')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción general')),
                ('responsable_nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre del responsable')),
                ('responsable_cargo', models.CharField(blank=True, max_length=200, verbose_name='Cargo del responsable')),
                ('firma_biomedico', models.TextField(blank=True, verbose_name='Firma del biomédico')),
                ('firma_responsable', models.TextField(blank=True, verbose_name='Firma del responsable')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('ingeniero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo', to=settings.AUTH_USER_MODEL, verbose_name='Ingeniero / Biomédico')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_trabajo', to='servicios.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='orden_trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos', to='mantenimiento.ordentrabajo', verbose_name='Orden de Trabajo'),
        ),
    ]
