# Generated by Django 6.0.7 on 2026-08-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_alter_mantenimiento_hoja_vida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='firma_biomedico',
            field=models.TextField(blank=True, verbose_name='Firma del biomédico'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='firma_responsable',
            field=models.TextField(blank=True, verbose_name='Firma del responsable'),
        ),
    ]
