# Generated by Django 6.0.7 on 2026-09-04 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_mantenimiento_firma_biomedico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='mantenimiento_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimiento_siguiente', to='mantenimiento.mantenimiento', verbose_name='Mantenimiento anterior'),
        ),
    ]
