# Generated by Django 6.0.7 on 2026-09-04 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_catalogoequipo_options_and_more'),
        ('mantenimiento', '0004_mantenimiento_mantenimiento_anterior'),
    ]

    operations = [
        migrations.CreateModel(
            name='MantenimientoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizada', models.BooleanField(default=False, verbose_name='Realizada')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ejecuciones', to='catalogo.actividadmantenimiento', verbose_name='Actividad')),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='mantenimiento.mantenimiento', verbose_name='Mantenimiento')),
            ],
            options={
                'verbose_name': 'Actividad de Mantenimiento',
                'verbose_name_plural': 'Actividades de Mantenimiento',
                'ordering': ['actividad__orden'],
                'constraints': [models.UniqueConstraint(fields=('mantenimiento', 'actividad'), name='unique_mantenimiento_actividad')],
            },
        ),
    ]
